# Generated by Django 5.2.4 on 2025-07-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='types',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shop.types'),
        ),
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.category'),
        ),
    ]
